version: 2
jobs:
  build:
    docker:
      - image: node:12.4-alpine
    steps:
      - run:
          name: install bash and git
          command: apk update && apk upgrade && apk add --no-cache bash git
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint && npm run prettier:check
      - run:
          name: test
          command: npm test
